name: Make
on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  make:
    name: Make
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Make
      run: ./make.sh
